{application,maze,
             [{applications,[kernel,stdlib,elixir,logger,postgrex,ecto_sql]},
              {description,"maze"},
              {modules,['Elixir.Dispatcher','Elixir.Maze',
                        'Elixir.Maze.Application','Elixir.Maze.Repo',
                        'Elixir.Maze.User','Elixir.Receiver','Elixir.Router',
                        'Elixir.Sorter','Elixir.Transformer']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
